'use client';
import React from 'react';

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-[#1a1a1a] text-white flex flex-col items-center py-20 px-4 sm:px-8">
      <div className="max-w-4xl w-full">
        <h1 className="text-3xl md:text-5xl font-bold mb-8 text-[#ef6b23]">PRIVACY POLICY</h1>
        
        <div className="space-y-8 text-gray-300 bg-[#2a2a2a] p-6 md:p-10 rounded-[20px] border border-white/10 shadow-lg leading-relaxed text-sm md:text-base">
          
          <section className="space-y-4">
            <p>
              CoBuild L.L.P, CIN No. [ CIN NO ] (“Company”, "We", "Us", or "Our"), a Private Limited Company with its registered office at [ Address ] which operates the website www.cobuild.capital (referred to as the “Platform”) is committed to protecting Your privacy and the information that You share while using the Platform. We value the trust You place in Us. Therefore, We maintain the highest security standards for securing the transactions and Your Information (defined below). We may also allow Our group/affiliate entities to use Our Platform to offer their products and services to You, in accordance with this privacy policy and under applicable terms and conditions specified on Our Platform.
            </p>
            <p>
              This privacy policy ("Privacy Policy") specifies the manner in which Your personal data and other information is collected, received, stored, processed, disclosed, transferred, dealt with or otherwise handled by the Company in relation to the services offered on the Platform (“Services”). This Privacy Policy does not apply to information that You provide to, or that is collected by, any third-party, and any third-party sites that You access or use in connection with the services offered on the Platform.
            </p>
            <p>
              Please read the Privacy Policy carefully prior to using or registering on the Platform or accessing any material, information or availing any Services through the Platform.
            </p>
            <p>
              By clicking the “Continue / I Accept” button provided at the sign-up page for the Platform, users ("You”, "Your" as applicable) accept and agree to be bound by the terms and conditions of this Privacy Policy. This Privacy Policy is incorporated into Our <a href="/terms" className="text-[#ef6b23] hover:underline">Terms of Use</a> (“Terms”) and shall be read harmoniously and in conjunction with the Terms. All capitalized terms used and not defined in this Privacy Policy shall have the meaning ascribed to them under the Terms.
            </p>
            <p>
              This Privacy Policy (i) is an electronic record under the Information Technology Act, 2000 read with rules and regulations made thereunder and is generated by a computer system; and (ii) will not require any physical, electronic, or digital signature.
            </p>
          </section>

          <section>
            <h2 className="text-xl md:text-2xl font-semibold text-white mb-4">1. Collection of Information:</h2>
            <ul className="space-y-4 list-none">
              <li>
                <span className="font-semibold text-white block mb-2">1.1.</span>
                We collect Personal Information (defined below) from You when You register or set up an account with Us, login on the Platform, fill up the ‘contact us’; ‘EOI’ or any such form, or interact with the customer support staff. You may browse certain sections of the Platform without being registered with Us. However, to avail the Services on the Platform You are required to set up an account with Us.
              </li>
              <li>
                <span className="font-semibold text-white block mb-2">1.2. This Privacy Policy applies to the following information:</span>
                <div className="ml-4 md:ml-8 space-y-4">
                  <div>
                    <p className="font-medium text-white mb-1">(i) Information You give Us:</p>
                    <p className="mb-2">When You start using the Platform, You may provide certain information to Us voluntarily while registering on Our Platform or in the course of availing Our Services, including Your name, email address and mobile number. We may collect this information through various means and in various places through the Platform, including account registration forms, contact us forms, or when You otherwise interact with the Platform including with customer support. Additionally, you may also be required to provide your PAN number, Aadhaar card, Passport, bank account details, TIN Number and any National Identification Number and type and/or scanned copies of the card, documents evidencing such details, and Your signature.</p>
                    <p className="mb-2">All such information disclosed by You shall be deemed to be disclosed willingly and without any coercion. No liability pertaining to the authenticity / genuineness / misrepresentation / fraud / negligence of the information disclosed shall lie on the Company nor will the Company be in any way responsible to verify any information obtained from You.</p>
                    <p className="mb-2">Certain features of the Platform may be restricted, unavailable or unusable if You choose not to provide certain information.</p>
                    <p className="mb-2">The above information is collectively referred to as (“Personal Information”).</p>
                    <p className="mb-2"><span className="font-semibold text-white">How We use this information:</span> We use the Personal Information specified in sub-point (i) for the following: (i) sending Platform and Services related communication such as details on buy/sell events on the Platform and (ii) undertaking Your identity verification (which includes sending OTP to registered mobile number for verification/sign in) and completion of Your KYC process, for registration and onboarding purposes, and to pre-populate relevant fields in the course of the Platform interface. Additionally, we may require Your signature for the purposes of executing certain investment documents and to avail the Services. Please note that the act of providing Your National Identification Documents like Aadhaar card, SS Card is voluntary in nature, and the Company hereby agrees and acknowledges that We will collect, use, and store Your Aadhaar card, Passport or any National Identity document only in compliance with applicable laws and this Privacy Policy. Please note that the Company stores Your Aadhaar details and other Personal Information collected only after masking the information.</p>
                  </div>
                  <div>
                    <p className="font-medium text-white mb-1">(ii) Non - Personal and Automatic Information:</p>
                    <p className="mb-2">We may also collect certain non-personal information, such as Your IP Address, web request, operating system, browser type, URL, internet service provider, aggregate user data, software and hardware attributes, pages You visit, and cookie information, etc., which will not identify You specifically (“Non-Personal Information”), while You browse, access or use the Platform. We receive and store Non–Personal Information by the use of data collection devices such as “cookies” on certain pages of the Platform. We offer certain additional features on the Platform that are only available through the use of such cookies. We place both permanent and temporary cookies in Your computer/mobile device’s storage drive.</p>
                    <p className="mb-2"><span className="font-semibold text-white">How We use this information:</span> We use such Non-Personal Information for the purpose of identifying and resolving any technical glitches that may be identified from such information, and for improving the overall functionality of the Platform. Additionally, this information is used to help and analyze Our Platform flow, track user trends, measure promotional effectiveness, and promote trust and safety. We retain such Non-Personal Information as necessary to resolve disputes, provide customer support and troubleshoot problems as permitted by law. However, please note that we do not track the behaviour of Users that are considered children/ minors in accordance with the laws of the relevant jurisdiction.</p>
                  </div>
                  <div>
                    <p className="font-medium text-white mb-1">(iii) User communications:</p>
                    <p className="mb-2">If You choose to post messages on Our message boards, chat rooms or other message areas or leave feedback, We will collect and store such information You provide to Us. If You send us correspondence, such as emails or letters, or if other users or third parties send us correspondence about Your activities or postings on the Platform, We may collect and retain such information into a file specific to You for responding to Your request and addressing concerns in relation to Your use of the Platform.</p>
                    <p className="mb-2"><span className="font-semibold text-white">How We use this information:</span> We retain this information as necessary to resolve disputes, provide customer support, respond to queries, and inquires, and troubleshoot problems and improve the Services.</p>
                  </div>
                </div>
              </li>
              <li><span className="font-semibold text-white">1.3.</span> Your Personal Information, Non-Personal Information and other information listed above shall together be referred to as “Your Information”.</li>
              <li><span className="font-semibold text-white">1.4.</span> While We are responsible under applicable laws in India to ensure completeness, accuracy, and consistency of Your Personal Information. We cannot comply with this obligation without Your due co-operation. You acknowledge and agree that You shall be responsible for ensuring that the Personal Information that You provide to Us is accurate, complete and current, and that You will co-operate with Us to ensure that such Personal Information is complete, accurate and consistent till such time it is being processed by Us. Additionally, You also agree that all the information furnished by You is lawful, and does not violate or infringe any laws. In case of any violations, infringement, furnishing of wrongful or unauthorized information, the Company shall not be liable to You or to any third party for the same.</li>
              <li><span className="font-semibold text-white">1.5.</span> All information gathered by the Company shall be stored on servers, log files and any other storage system owned by the Company or by third parties in India. Our primary goal in doing so is to provide You a safe, efficient, smooth, and customized experience on the Platform.</li>
              <li><span className="font-semibold text-white">1.6.</span> We also do not voluntarily or actively collect, process, use or disclose any personal information of children/minors (in accordance with the threshold for minimum age in the relevant jurisdiction), or of persons with disabilities, without the verifiable prior consent of the parents or lawful guardians of the child/minor or person with disability. If We learn that We have collected the personal information of a child/minor or of a person with disability without first receiving the verifiable consent of their parent or lawful guardian, We will take steps to delete such personal information in a manner consistent with applicable laws of India, as soon as reasonably possible.</li>
              <li><span className="font-semibold text-white">1.7.</span> As a matter of principle, We do not collect certain special categories of Personal Information about You such as details about Your race or ethnicity, religious or philosophical beliefs, sexual orientation, political opinions, information about Your health or any genetic information.</li>
              <li><span className="font-semibold text-white">1.8.</span> We may obtain some of Your Information including Personal Information from third parties, or from publicly available sources. The third parties from who We obtain Your information include Our business partners, independent service providers, Our group entities, various merchants, marketplaces, re-sellers, payment partners, payment aggregators, payments systems, or payment service providers, on Your behalf. You hereby provide Your unconditional consent for Us to do so subject to the applicable law in India for the time being in force.</li>
              <li><span className="font-semibold text-white">1.9.</span> The information collected allows Us to provide the Services and features on the Platform that most likely meet Your needs, and to customize the Platform to make Your experience safer and easier. More importantly, while doing so, We collect Your Information from You that We consider necessary for achieving this purpose. In addition, the Company / Platform may store specific information, including those applicable to any Users of the Platform on a blockchain application of Company’s choice and offer limited access to the Users and to pre-sanctioned external stakeholders, including but not limited to regulators, statutory bodies, auditors, trustees, administrators, escrow agents etc., ("Blockchain Access”). The Company / Platform in this regard may furnish Users with a personal “Blockchain Key”, which may be used by You to access information specific to You, through an independent digital application outside of the Platform. Upon Your registration on the Platform, You authorize the Company to enable such Blockchain Access for Your account.</li>
              <li><span className="font-semibold text-white">1.10.</span> We also use cookies to allow You to enter Your password less frequently during a session on the Platform. Most cookies are “session cookies,” meaning that they are automatically deleted from Your storage drive at the end of a session. To provide a better experience to You, We also store certain “session cookies” on Your device, so that You do not lose Your last browsed page and can continue using the Platform seamlessly in case of network outage or unexpected sign out from the Platform. You are always free to decline Our cookies by taking specific action at your end, if Your browser permits, although in that case, You may not be able to use certain features or Services being provided on the Platform or You may be required to re-enter Your password each time You log – in or access the Platform during a session.</li>
              <li><span className="font-semibold text-white">1.11.</span> In general, You can browse the Platform without telling Us who You are or revealing any Personal Information about Yourself. In such a case, We will only collect and store the Non – Personal Information. Once You give us Your Personal Information, You are not anonymous to Us. Wherever possible, while providing the information to Us, We indicate which fields are mandatory and which fields are optional for You. You always have the option to not provide the Personal Information to Us through the Platform by choosing to not use a particular Service, which requires You to provide such information. We may automatically track certain information about You based upon Your behavior on the Platform. We use this information to do internal research on Your demographics, interests, and behavior to better understand, protect and serve You. This information is compiled and analyzed by the Company on an aggregated basis and not individually, in a manner that does not specifically identify You.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl md:text-2xl font-semibold text-white mb-4">2. Use of information:</h2>
            <ul className="space-y-4 list-none">
              <li><span className="font-semibold text-white">2.1.</span> We use Your Information, for the following: (i) To create Your login credentials to establish Your account; (ii) to provide and improve the Services and features on the Platform that You request; (iii) to resolve disputes and troubleshoot problems; (iv) to help promote a safe service on the Platform and protect the security and integrity of the Platform, the Services and the users; (v) to customize Your experience on the Platform or share marketing material with You; (vi) to detect, prevent and protect Us from any errors, fraud and other criminal or prohibited activity on the Platform; (vii) to enforce and inform about our terms and conditions; (viii) to process and fulfil Your request for Services or respond to Your comments, and queries on the Platform; (ix) to contact You; (x) to communicate important notices or changes in the Services provided by the Company, use of the Platform and the terms which govern the relationship between You and Us; (xi) for any other purpose after obtaining Your consent at the time of collection; and (xii) sharing and disclosure of data with third parties. Any collection of additional information and documents shall be subject to Your consent after intimating You of the purpose for such collection.</li>
              <li><span className="font-semibold text-white">2.2.</span> We may occasionally ask You to complete optional online surveys. These surveys may ask You for Your contact information and demographic information (like zip code, age etc.,). We use this information to tailor Your experience at the Platform, providing You with content that We think You might be interested in and to display content according to Your preferences.</li>
              <li><span className="font-semibold text-white">2.3.</span> We use Your Personal Information to send You communications regarding the Services, as well as send You promotional emails / transaction updates, however, We will provide You the ability to opt-out of receiving such emails from Us If You opt out, the Company may still send You non-promotional emails, such as emails about the Services and Your account on the Platform. Unless and until You explicitly give Your consent to Us to do so, We will not share Your Personal Information with another user of the Platform and vice versa.</li>
              <li>
                <span className="font-semibold text-white block mb-2">2.4.</span>
                Notwithstanding anything contained herein, the Company may, in compliance with applicable laws in India, process Your Personal Information without obtaining Your consent in the event: (i) You have voluntarily provided Your Personal Information to Us, and You have not indicated to Us that You do not consent to Our use of such Personal Information; (ii) the purpose is for the State and any of its instrumentalities to provide or issue to You such subsidy, benefit, service, certificate, licence or permit as may be prescribed by the Central Government; (iii) the purpose is for performance by the State or any of its instrumentalities of any function under any law for the time being in force in India or in the interest of sovereignty and integrity of India or security of the State; (iv) the purpose is for fulfilling any obligation under any law for the time being in force in India on any person to disclose any information to the State or any of its instrumentalities, subject to such processing being in accordance with the provisions regarding disclosure of such information in any other law for the time being in force; (v) the purpose is for compliance with any judgment or decree or order issued under any law for the time being in force in India, or any judgment or order relating to claims of a contractual or civil nature under any law for the time being in force outside India; (vi) the purpose is for responding to a medical emergency involving a threat to the life or immediate threat to Your health of or any other individual; (vii) the purpose is for taking measures to provide medical treatment or health services to any individual during an epidemic, outbreak of disease, or any other threat to public health; (viii) the purpose is for taking measures to ensure safety of, or provide assistance or services to, any individual during any disaster, or any breakdown of public order. In such an event the Company is in no manner responsible for informing You or seeking Your approval or consent.
                <p className="mt-4 mb-2">To ensure transparency, we link specific data points to their primary use cases. We only collect information necessary to provide our Services.</p>
                <div className="overflow-x-auto mt-4">
                  <table className="w-full text-left border-collapse border border-white/20">
                    <thead>
                      <tr className="bg-[#3a3a3a]">
                        <th className="border border-white/20 p-3 font-semibold text-white">Personal Data Point</th>
                        <th className="border border-white/20 p-3 font-semibold text-white">Specific Use Case / Purpose</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td className="border border-white/20 p-3">Full Name</td>
                        <td className="border border-white/20 p-3">To identify you as a registered user and personalize your experience.</td>
                      </tr>
                      <tr>
                        <td className="border border-white/20 p-3">Email Address</td>
                        <td className="border border-white/20 p-3">To send account notifications, security alerts, and requested newsletters.</td>
                      </tr>
                      <tr>
                        <td className="border border-white/20 p-3">Phone Number</td>
                        <td className="border border-white/20 p-3">Specifically to contact you for future updates, critical support, and authentication.</td>
                      </tr>
                      <tr>
                        <td className="border border-white/20 p-3">KYC Docs (PAN, Aadhaar, Passport)</td>
                        <td className="border border-white/20 p-3">Mandatory identity verification and regulatory compliance for financial services.</td>
                      </tr>
                      <tr>
                        <td className="border border-white/20 p-3">Bank Account Details</td>
                        <td className="border border-white/20 p-3">To facilitate transactions, payouts, and investment distributions.</td>
                      </tr>
                      <tr>
                        <td className="border border-white/20 p-3">IP Address & Device Info</td>
                        <td className="border border-white/20 p-3">To resolve technical glitches, improve Platform functionality, and prevent fraud.</td>
                      </tr>
                      <tr>
                        <td className="border border-white/20 p-3">User Communications (Chat/Email)</td>
                        <td className="border border-white/20 p-3">To troubleshoot specific problems and address your inquiries.</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl md:text-2xl font-semibold text-white mb-4">3. Sharing of Information:</h2>
            <ul className="space-y-4 list-none">
              <li><span className="font-semibold text-white">3.1.</span> Access to your Personal Information will be provided to some of Our employees strictly on a need-to-know basis. With Your consent, We may also disclose Your Personal Information to third party vendors, partnered organizations, consultants, bankers, payment gateways, escrow agents, trustees, administrators, auditors, accountants, technology vendors, KYC verification partners, data storage companies and other service providers etc., who work for the Company or provide Services through the Platform and are bound by contractual obligations to keep such Personal Information confidential and use it only for the purposes for which We disclose it to them. This disclosure may be required for Us, for instance, to provide You access to Our Services, to facilitate and assist Our marketing and advertising activities/initiatives, for undertaking auditing or data analysis, or to prevent, detect, mitigate, and investigate fraudulent or illegal activities related to Our Services.</li>
              <li><span className="font-semibold text-white">3.2.</span> We use a variety of third-party service providers and vendors to help Us provide the Services to You. For example, service providers which assist Us to: (i) verify Your identity or authenticate Your identification documents; (ii) perform product development, software and website maintenance and debugging; (iii) allow the provision of the Services through third party platforms and software tools (e.g. through the integration with our API’s); (iv) provide customer service, advertising, or payments services; (v) processing payments including validation of Your bank accounts and account information; (vi) to facilitate and assist Our marketing and advertising activities/initiatives; (vii) for undertaking auditing or data analysis; or (viii) to prevent, detect, mitigate, and investigate fraudulent or illegal activities related to Our Services. These providers have access to Your Personal Information to the extent required to perform these tasks on Our behalf and are contractually bound to protect and to use it only for the purposes for which it was disclosed and consistent with this Privacy Policy. In this regard, You specifically agree and consent to Us collecting, transferring, and sharing information (including Personal Information) related to You with third party service providers solely for providing Services to You including processing Your requests to avail the Services. You may request to view the names of third parties with whom We share Your information.</li>
              <li><span className="font-semibold text-white">3.3.</span> The Company may also disclose Your Information, to the extent necessary: (i) to comply with applicable laws and to respond to lawful requests and legal process, (ii) to protect the rights and property of the Company, Our users, and others, including to enforce the Terms, and (iii) in an emergency to protect the personal safety and assets of the Company, the users, or any person. In such an event the Company is in no manner responsible for informing You or seeking Your approval or consent.</li>
              <li><span className="font-semibold text-white">3.4.</span> We may, in compliance with applicable laws, share/transfer/assign all of Your Information with any other business entity(ies), in the event of a merger, sale, re-organization, amalgamation, joint ventures, assignment, restructuring of business or transfer or disposition of all or any portion of Our business.</li>
              <li><span className="font-semibold text-white">3.5.</span> We do not disclose Your Personal Information to third parties for their marketing and advertising purposes without Your explicit consent.</li>
              <li><span className="font-semibold text-white">3.6.</span> You agree and explicitly consent to disclosure of Your Personal Information to such third-parties and for such purposes as mentioned in this Clause 3. Please note that to this extent, you will also be subject to the terms of use and privacy policy that is maintained by such third-party service providers.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl md:text-2xl font-semibold text-white mb-4">4. Security Precautions and Measures:</h2>
            <ul className="space-y-4 list-none">
              <li><span className="font-semibold text-white">4.1.</span> Our Platform has reasonable security measures and safeguards in place to protect Your privacy and Personal Information from loss, misuse, unauthorized access, disclosure, destruction, and alteration of the information in compliance with applicable laws. Further, whenever You change or access Your Account on the Platform or any information relating to it, We offer the use of a secure server. We cannot however ensure or warrant the security of any information You transmit to the Company or guarantee that Your Information provided for availing the Services or Platform may not be accessed, disclosed, altered, or destroyed by a breach of any of Our security measures and safeguards. It is further clarified that You have and so long as You access and/or use the Platform (directly or indirectly) the obligation to ensure that You shall at all times take adequate physical, managerial, and technical safeguards, at Your end, to preserve the integrity and security of Your data which shall include and not be limited to Your Personal Information.</li>
              <li><span className="font-semibold text-white">4.2.</span> This Privacy Policy and the security controls and practices implemented by the Company to protect Your Personal Information shall be the reasonable security practices and procedures under section 43A of the Information Technology Act, 2000, or any other reasonable security practices and procedures that may be stipulated under any applicable law for the time being in force.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl md:text-2xl font-semibold text-white mb-4">5. Links to Other third-party sites and collection of information:</h2>
            <ul className="space-y-4 list-none">
              <li><span className="font-semibold text-white">5.1.</span> Our Platform may provide links to other third-party Platforms (“Third-Party Sites”) that may collect Your Personal Information including Your IP Address, browser specification, or operating system. The Company is not in any manner responsible for the security of such information or their privacy practices or content of those third-party sites. Additionally, You may also encounter “cookies” or other similar devices on certain pages of the Third-Party Sites and it is hereby clarified by the Company that it does not control the use of cookies by these Third-Party Sites. These third-party service providers and Third-Party Sites may have their own privacy policies governing the storage and retention of Your Information that You may be subject to. This Privacy Policy does not govern any information provided to, stored on, or used by these third-party providers and Third-Party Sites. We recommend that when You enter a Third-Party Site, You review the Third-Party Site's privacy policy as it relates to safeguarding of Your Information. You agree and acknowledge that We are not liable for the information published in search results or by any Third-Party Sites.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl md:text-2xl font-semibold text-white mb-4">6. Public Posts:</h2>
            <ul className="space-y-4 list-none">
              <li><span className="font-semibold text-white">6.1.</span> You may provide Your feedback, reviews, testimonials, etc. on the Platform on Your use of the Services provided by the Company ("Posts"). Any content or Personal Information and Posts that You share or upload on the publicly viewable portion of the Platform will be publicly available and can be viewed by other users. Your Posts shall have to comply with the conditions relating to use of Platform as mentioned in the Terms. The Company retains an unconditional right to remove and delete any Post or such part of the Post that, in the opinion of the Company, does not comply with the conditions in the Terms. The Company reserves the right to use, reproduce and share Your Posts for any purpose. If You delete Your Posts from the Platform, subject to compliance with the applicable laws, copies of such Posts may remain viewable in archived pages, or such Posts may have been copied or stored by other Users.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl md:text-2xl font-semibold text-white mb-4">7. Your rights and changes to Privacy Policy:</h2>
            <ul className="space-y-4 list-none">
              <li><span className="font-semibold text-white">7.1. Withdrawal of consent:</span> You may choose to withdraw Your consent (including consent provided for processing of Your Personal Information or other information by Us or by any third party on our behalf) provided hereunder at any point in time. Such withdrawal of the consent must be sent in writing to <a href="mailto:Support@cobuild.capital" className="text-[#ef6b23]">Support@cobuild.capital</a>. In case You do not provide Your consent or later withdraw Your consent, We request You not to access the Platform or use the Services and also reserve the right to not provide You any Services on the Platform. In such a scenario, the Company may delete Your Information or de-identify it so that it is anonymous and not attributable to You. In the event, the Company retains the Personal Information post withdrawal or cancellation of Your consent, it shall retain it only for the period permitted under applicable laws.</li>
              <li><span className="font-semibold text-white">7.2. Modifying or correcting inaccuracies in the information:</span> In the event that any Personal Information already provided by You is inaccurate, incomplete or outdated, You may correct or update any such information online. You have the right to ask Us to correct inaccurate or incomplete or misleading Personal Information concerning You or update Your Personal Information (which You cannot update yourself online) by contacting <a href="mailto:Support@cobuild.com" className="text-[#ef6b23]">Support@cobuild.com</a>. In the event of loss of access details, You may retrieve the same or receive new access details by sending an e-mail to: <a href="mailto:Support@cobuild.com" className="text-[#ef6b23]">Support@cobuild.com</a>.</li>
              <li><span className="font-semibold text-white">7.3. Right to Erasure:</span> This is also known as ‘the right to be forgotten’ and, in simple terms, enables You to request the deletion or removal of Your Information where there’s no compelling reason for Us to keep it. Such right of erasure can be exercised by writing to Us at <a href="mailto:Support@cobuild.com" className="text-[#ef6b23]">Support@cobuild.com</a>. This is not a general right to erasure; there are exceptions, such as when the law requires Us to retain certain Personal Information about You and the transactions You have executed on the Platform or where such retention is required for providing the Services to You, etc. On such a request for erasure, we shall delete all Your Personal Information stored by Us, as well as ensure that any third party service provider processing Your Personal Information on behalf of us deletes all Your Personal Information, unless retention of the same is necessary for the providing the Services or for compliance with any applicable law for the time being in force.</li>
              <li><span className="font-semibold text-white">7.4. Right to certain information:</span> You have the right to ask Us for a (i) summary of Your Personal Information being processed by Us and the processing activities undertaken by Us with respect to such Personal Information; and (ii) the identities of all other third party entities with whom Your Personal Information has been shared by Us, along with a description of the Personal Information so shared, except when such sharing is pursuant to a written request by such entity (authorized by law) who obtains the information for the purpose of prevention or detection or investigation of offences or cyber incidents, or for prosecution or punishment of offences.</li>
              <li><span className="font-semibold text-white">7.5. Right to nominate:</span> You shall have the right to nominate, in a manner prescribed by the Central Government, any other individual, who shall, in the event of Your death or incapacity, exercise Your rights in relation to Your Personal Information, in accordance with applicable law in India.</li>
              <li><span className="font-semibold text-white">7.6. Use of a consent manager:</span> You are permitted to give, manage, review or withdraw Your consent provided to Us to process Your Personal Information through a ‘consent manager’. A consent manager is an entity that is registered with the Data Protection Board. The consent manager is accountable to You and can assist you in providing or withdrawing your consent to Us to process Your Personal Information, on Your behalf. Such consent managers must comply with the obligations imposed on them as may be prescribed by the Central Government.</li>
              <li><span className="font-semibold text-white">7.7. Changes To Our Privacy Policy:</span> We reserve the unconditional right to change, modify, add, or remove portions of this Privacy Policy at any time, by notifying You of such changes. Any changes or updates will be effective immediately. You should review this Privacy Policy regularly for changes. You can determine if changes have been made by checking the “Last Updated” legend above.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl md:text-2xl font-semibold text-white mb-4">8. Data Retention and Deletion</h2>
            <ul className="space-y-4 list-none">
              <li><span className="font-semibold text-white">8.1.</span> We shall be entitled to retain Your Information for such duration as may be required for the purposes specified hereunder or for such other periods as may be required under the applicable laws and the said information will be used by Us only in accordance with this Privacy Policy. However, We may retain Your Information if we believe it may be necessary to prevent fraud or future abuse, to enable Us to exercise our legal rights and/or defend against legal claims or if required by law or for other legitimate purposes. Notwithstanding anything contained herein, We will not retain your Personal Information and other information for longer than the periods provided below:
                <div className="overflow-x-auto mt-4">
                  <table className="w-full text-left border-collapse border border-white/20">
                    <thead>
                      <tr className="bg-[#3a3a3a]">
                        <th className="border border-white/20 p-3 font-semibold text-white">Type of Data</th>
                        <th className="border border-white/20 p-3 font-semibold text-white">Data Retention Period</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td className="border border-white/20 p-3">Personal Information</td>
                        <td className="border border-white/20 p-3">End of Your relationship with Us + 5 years</td>
                      </tr>
                      <tr>
                        <td className="border border-white/20 p-3">Non-personal Information</td>
                        <td className="border border-white/20 p-3">As required under applicable laws</td>
                      </tr>
                      <tr>
                        <td className="border border-white/20 p-3">User Communications</td>
                        <td className="border border-white/20 p-3">End of Your relationship with Us + 3 years</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </li>
              <li><span className="font-semibold text-white">8.2.</span> We shall be entitled to retain Your Information for such duration as specified above, and Your Information will be used by Us only in accordance with this Privacy Policy. You acknowledge that if We determine that any information You have provided or uploaded violates the terms of this Privacy Policy, We have the right, in our absolute discretion, to delete or destroy such Your Information without incurring any liability to You.</li>
              <li><span className="font-semibold text-white">8.3.</span> You hereby agree, acknowledge and grant Your consent enabling Us to retain Your Personal Information for Our compliance under applicable laws including but not limited to the Prevention of the Money Laundering Act, 2002 or the Prevention of Money Laundering (Maintenance of Records) Rules, 2005 as amended, modified/ reenacted from time to time and/ or any other guidelines/policies issued by government/ statutory authorities or any regulatory bodies in this regard.</li>
              <li><span className="font-semibold text-white">8.4.</span> When the retention period for Your Personal Information as outlined above expires, We will actively destroy/delete such Personal Information from our systems. We may, however, continue to retain Your Personal Information in anonymized form for analytical and research purposes. However, We shall not retain Your Personal Information if it is no longer required by Us and there is no legal requirement to retain the same. Do note that multiple legal bases may exist in parallel, and We may still have to retain certain data and information at any time.</li>
              <li>
                <span className="font-semibold text-white block mb-2">8.5. We maintain rigorous security standards to protect your information. However, in the event of a security lapse:</span>
                <span className="font-semibold text-white">Mandatory Notification:</span> In the event of a personal data breach, we will notify the Data Protection Board of India and the affected Data Principals in the manner prescribed under applicable law.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl md:text-2xl font-semibold text-white mb-4">9. Your Duties:</h2>
            <ul className="space-y-4 list-none">
              <li>
                <span className="font-semibold text-white block mb-2">9.1. You shall, at all times, ensure that:</span>
                <div className="ml-4 md:ml-8 space-y-2">
                  <p>(i) While exercising Your rights under applicable data protection law, you must comply with the provisions of all applicable laws in India;</p>
                  <p>(ii) You do not impersonate another person while providing Your Personal Information for a purpose specified to You at the time of collecting such Personal Information;</p>
                  <p>(iii) You do not suppress any material information while providing Your Personal Information for any document, unique identifier, proof of identity, proof of citizenship or proof of address issued by the Central Government or any of its instrumentalities;</p>
                  <p>(iv) You do not to register a false or frivolous grievance or complaint with the Grievance Redressal Officer or the Data Protection Board;</p>
                  <p>(v) You furnish only such information as is verifiably authentic, while exercising Your right to modification, correction, update or erasure under applicable laws in India.</p>
                </div>
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl md:text-2xl font-semibold text-white mb-4">10. Language Accessibility (DPDPA Section 5(3))</h2>
            <p className="mb-4">In accordance with Section 5(3) of The Digital Personal Data Protection Act, 2023, we are committed to ensuring you understand how your data is handled.</p>
            <ul className="list-disc ml-6 md:ml-8 space-y-2">
              <li><span className="font-semibold text-white">Request for Translation:</span> This Privacy Policy is available in English. However, you may request a copy of this notice in any of the 22 languages specified in the 8th Schedule of the Indian Constitution (including Hindi, Bengali, Gujarati, Kannada, Marathi, Tamil, Telugu, and others).</li>
              <li><span className="font-semibold text-white">How to Request:</span> Please send an email to <a href="mailto:Support@cobuild.capital" className="text-[#ef6b23]">Support@cobuild.capital</a> with the subject line "Language Access Request."</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl md:text-2xl font-semibold text-white mb-4">11. Grievance Officer:</h2>
            <p className="mb-4">You have the right to readily available means of grievance redressal in respect of any act or omission committed by Us or your consent manager regarding the performance of our obligations under this Privacy Policy or the exercise of Your rights in relation to Your Personal Information. If You have any grievance with respect to the Platform or the Services, You may write to the grievance officer, the name and contact details have been provided below:</p>
            <div className="mb-4 p-4 bg-[#3a3a3a] rounded-lg border border-white/10">
              <p><span className="font-semibold text-white">Name:</span> Jawwad Sayed</p>
              <p><span className="font-semibold text-white">Email:</span> <a href="mailto:Compliance@cobuild.capital" className="text-[#ef6b23]">Compliance@cobuild.capital</a></p>
            </div>
            <p>In the event You have exhausted Your opportunity of redressing your grievances with respect to Your Personal Information through the Grievance Redressal Officer, you may approach the Data Protection Board established under the Digital Personal Data Protection Act, 2023, in a manner as may be prescribed by the Central Government.</p>
          </section>

          <section>
            <h2 className="text-xl md:text-2xl font-semibold text-white mb-4">12. Questions?</h2>
            <p className="mb-6">Please feel free to contact us at <a href="mailto:Support@cobuild.com" className="text-[#ef6b23]">Support@cobuild.com</a> regarding any questions on the Privacy Policy.</p>
            
            <div className="pt-8 border-t border-white/10">
              <h3 className="text-lg font-semibold text-white mb-2">COBUILD CAPITAL L.L.P</h3>
              <p>CIN: [1282394892302031].</p>
              <p>Website: <a href="https://www.cobuild.capital" target="_blank" rel="noopener noreferrer" className="text-[#ef6b23] hover:underline">www.cobuild.capital</a></p>
              <p>Email ID: <a href="mailto:Compliance@cobuild.capital" className="text-[#ef6b23] hover:underline">Compliance@cobuild.capital</a></p>
              <p>Address: Address line 1, line 2, Mumbai: 4000XX Maharashtra, India.</p>
            </div>
          </section>

        </div>
      </div>
    </div>
  );
}
